# Generated by Django 5.0.6 on 2024-06-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_image_upload', '0002_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='Untitled Post')),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('like_count', models.SmallIntegerField(default=0)),
                ('post_images', models.ManyToManyField(to='app_image_upload.image')),
                ('posted_by', models.ForeignKey(on_delete=models.SET('Deleted User'), to='app_image_upload.profile')),
            ],
        ),
    ]
