# Generated by Django 5.0.6 on 2024-06-04 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_image_upload', '0005_userpost_text_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='post_images',
        ),
    ]
