# Generated by Django 5.0.6 on 2024-06-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_image_upload', '0007_remove_userpost_like_count_userpost_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='post_images',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
