# Generated by Django 5.0.6 on 2024-06-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_image_upload', '0010_remove_image_posted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='likes',
            field=models.ManyToManyField(related_name='image_liked_by', to='app_image_upload.profile'),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='likes',
            field=models.ManyToManyField(related_name='post_liked_by', to='app_image_upload.profile'),
        ),
    ]
