# Generated by Django 5.0.6 on 2024-06-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_image_upload', '0011_image_likes_alter_userpost_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='text_content',
            field=models.TextField(max_length=1000),
        ),
    ]
