# Generated by Django 5.0.6 on 2024-06-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_image_upload', '0013_image_posted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='poster_name',
            field=models.TextField(default='ANW'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpost',
            name='poster_name',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
